apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-model-download
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: model-download
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: HUGGINGFACE_HUB_CACHE
              value: "/root/.cache/huggingface"
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: models
              mountPath: /app/models
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache-pvc
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc