apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-model-download
  labels:
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Chart.Name }}