apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{ if .Values.global.GPU.enabled }}
  name: egai-ovms-embed-gpu-pvc
  {{ else }}
  name: egai-ovms-embed-pvc
  {{ end }}
  annotations:
    helm.sh/resource-policy: {{ .Values.global.pvc_policy }}  # Prevent Helm from deleting PVC on uninstall
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.egai_ovms_embed_pvc.size }}
