global:
  egai_tgi_pvc:
    size: 20Gi
  
Chatqna:
  env:
    ENDPOINT_URL: http://text-generation-service

tgiService:
  name: text-generation-service
  enabled: true
  service:
    port: 8080
vllmService:
  name: vllm-service
  enabled: false
ovmsService:
  name: ovmsService
  enabled: false
  
